[versions]
kotlin = "2.2.21"
mikbot = "5.031"
ktor = "3.3.0"

[libraries]
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version = "1.9.0" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version = "0.7.1" }

mikbot-gdpr = { group = "dev.schlaubi", name = "mikbot-gdpr" }
mikbot-kubernetes = { group = "dev.schlaubi", name = "mikbot-kubernetes" }
mikbot-ktor = { group = "dev.schlaubi", name = "mikbot-ktor" }

java-string-similarity = { group = "info.debatty", name = "java-string-similarity", version = "2.0.0" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
mikbot = { id = "dev.schlaubi.mikbot.gradle-plugin", version.ref = "mikbot" }
ksp = { id = "com.google.devtools.ksp", version = "2.3.2" }
buildconfig = { id = "com.github.gmazzo.buildconfig", version = "5.6.8"}
